---
- name: nginx/git installation
  hosts: web
  gather_facts: yes
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes

  - name: "Install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: "Install git"
    apt:
      name: git
      state: latest
      update_cache: yes       

  - name: Clone depot git
    git:
      repo: https://github.com/bjausseran/pipeline_ansible.git
      dest: /var/www/html/
      clone: yes
